import { GeistSans } from "geist/font/sans";
import "./globals.css";

export const metadata = {
  title: "Scanner",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
